// { title: '', answer: '' },

// const questions = [

// ]


const questions = [
    { title: 'Architectural ', answer: 'kiến trúc' },
    { title: 'Achieve', answer: 'đạt được, hoàn thành, thi hành' },
    { title: 'Testable', answer: 'có thể kiểm tra được' },
    { title: 'Represent', answer: 'đại diện' },
    { title: 'Enforce', answer: 'thi hành, bắt buộc' },
    { title: 'Typically', answer: 'tiêu biểu là' },
    { title: 'Interaction', answer: 'sự tương tác' },
    { title: 'Specifies ', answer: 'chỉ định, xác định' },
    { title: 'Concern', answer: 'mối bận tâm, điều lo ngại' },
    { title: 'Concepts ', answer: 'các khái niệm' },
    { title: 'Belongs', answer: 'thuộc về' },
    { title: 'Aspect ', answer: 'diện mạo, tình trạng' },
    { title: 'Impacting ', answer: 'tác động, va chạm' },
    { title: 'Demonstrated ', answer: 'chứng minh' },
    { title: 'Callable', answer: 'có thể gọi được' },
    { title: 'Above', answer: 'ở trên, trên hết, trước hết' },
    { title: 'Appending', answer: 'nối lại' },
    { title: 'Supply', answer: 'cung cấp, tiếp tế' },
    { title: 'Preceding', answer: 'trước' },
    { title: 'Determines', answer: 'xác định' },
    { title: 'Cause', answer: 'nguyên nhân, gây ra' },
    { title: 'Explicitly', answer: 'rõ ràng' },
    { title: 'Modify', answer: 'biến đổi' },
    { title: 'Indicate', answer: 'biểu thị, trình bày' },
    { title: 'Encapsulates ', answer: 'gói lại, đóng gói' },
    { title: 'Referred', answer: 'giới thiệu' },
    { title: 'Navigate', answer: 'điều hướng' },
    { title: 'Occurrences', answer: 'lần xuất hiện' },
    { title: 'Omitted', answer: 'bỏ qua' },
    { title: 'Instead of', answer: 'thay vì' },
    { title: 'Slightly different', answer: 'hơi khác' },
    { title: 'Across', answer: 'băng qua' },
    { title: 'Apply across', answer: 'áp dụng qua' },
    { title: 'Maintaning', answer: 'duy trì' },
    { title: 'Maintainable', answer: 'có thể bảo trì' },
    { title: 'Directly', answer: 'trực tiếp, thẳng tới' },
    { title: 'Appropriate', answer: 'phù hợp' },
    { title: 'By having', answer: 'bằng cách đó' },

];


const newWords = [
    { title: 'Decoration', answer: 'đồ trang trí, huy chương, huân chương' },
    { title: 'Revive', answer: 'hồi phục, sống lại, tỉnh lại, hồi sinh' },
    { title: 'Dumbfound', answer: 'làm ai đó không nói được vì ngạc nhiên, làm điếng người' },
    { title: 'Crush', answer: 'phải lòng, mê ai đó' },
    { title: 'Descended', answer: 'có nguồn gốc từ' },
    { title: 'Advanced', answer: 'tiên tiến, tiến bộ' },
    { title: 'Cough', answer: 'ho, tiếng ho' },
    { title: 'Rejoice', answer: 'vui mừng, hân hoan' },
    { title: 'Shall', answer: 'sẽ (chỉ các dự đoán tương lai, ý chí, sự quyết tâm, lời đề nghị, gợi ý...)' },
    { title: 'Sell', answer: 'lừa bịp, bán, nhượng lại' },
    { title: 'Allowance', answer: 'tiền trợ cấp, thừa nhận, thú nhận' },
    { title: 'Earnestly', answer: 'nghiêm túc, nghiêm chỉnh' },
    { title: 'Attract', answer: 'thu hút, hấp dẫn' },
    { title: 'Signal', answer: 'dấu hiệu, tín hiệu, hiệu lệnh' },
    { title: 'Approach', answer: 'đến gần, lại gần, gần như' },
    { title: 'Useless', answer: 'vô dụng, không đem lại kết quả tốt' },
    { title: 'Coincidence', answer: 'sự trùng hợp ngẫu nhiên' },
    { title: 'Rely', answer: 'dựa vào, tin tưởng vào' },
    { title: 'Somehow / someway', answer: 'không biết phải làm sao, bằng cách nào đó' },
    { title: 'Naive', answer: 'ngây thơ, khờ dại' },
    { title: 'Ex', answer: 'cựu, nguyên, cũ' },
    { title: 'Line', answer: 'dòng dõi, ranh giới, giới hạn, phòng tuyến' },
    { title: 'Instinct', answer: 'bản năng' },
    { title: 'Anxious', answer: 'lo âu, băn khoăn' },
    { title: 'Hurdle', answer: 'khó khăn cần phải vượt qua, chướng ngại vật' },
    { title: 'Ignorant', answer: 'ngu dốt, dốt nát' },
    { title: 'Hardship', answer: 'sự gian khổ, sự thử thách gay go' },
    { title: 'Sufficient', answer: 'có khả năng, có thẩm quyền' },
    { title: 'Sufficiently', answer: 'đủ, thích đáng' },
    { title: 'Rather', answer: 'dĩ nhiên là có, đúng hơn, phần nào, hơi khá' },
    { title: 'Stuff', answer: 'thứ, món, đồ đạc' },
    { title: 'Expense', answer: 'sự tiêu, phí tổn' },
    { title: 'Haughtily', answer: 'kiêu căng, ngạo mạn' },
    { title: 'Negotiation', answer: 'đàm phán, thương lượng, dàn xếp' },
    { title: 'Ground', answer: 'mặt đất, nền' },
    { title: 'Judge', answer: 'quan tòa, thẩm phán, xét xử, phân xử' },
    { title: 'Undertake', answer: 'đảm nhận, cam kết, bảo đảm' },
    { title: 'Negotiate', answer: 'đàm phán, thương lượng, dàn xếp' },
    { title: 'Triumphant', answer: 'đắc thắng, vui mừng, hân hoan' },
    { title: 'Composure', answer: 'sự bình tĩnh, sự điềm tĩnh' },
    { title: 'Sequel', answer: 'hậu quả, ảnh hưởng, kết quả' },
    { title: 'Holding', answer: 'cổ phần, đất thuê mướn' },
    { title: 'Hold', answer: 'cầm, nắm, giữ, theo đuổi' },
    { title: 'Commonwealth', answer: 'liên bang, toàn thể nhân dân' },
    { title: 'Commonweal', answer: 'phúc lợi chung' },
    { title: 'Smirk', answer: 'cười tự mãn' },
    { title: 'Explanation', answer: 'lời giải thích, thanh minh' },
    { title: 'Blunt', answer: 'lỗ mãng, đần độn' },
    { title: 'Obvious', answer: 'rõ ràng, rành mạch, hiển nhiên' },
    { title: 'Highness', answer: 'mức cao, sự cao quý, hoàng thân, hoàng tử, công chúa, điện hạ' },
    { title: 'Such', answer: 'như thế, như vậy, thật là, quả là' },
    { title: 'Perk', answer: 'ngẩng đầu, vênh mặt' },
    { title: 'Graduation', answer: 'tốt nghiệp, bắng cấp tốt nghiệp' },
    { title: 'Guardian', answer: 'người canh gác, người bảo vệ' },
    { title: 'Deity', answer: 'vị thần' },
    { title: 'Hall', answer: 'đại sảnh, hội trường, trụ sở lớn' },
    { title: 'Audience', answer: 'khán giả, thính giả, sự yết kiến, sự tiếp kiến' },
    { title: 'Mention', answer: 'đề cập, kể ra, nói đến' },
    { title: 'Inconsequence', answer: 'hậu quả, không hợp lý' },
    { title: 'Concubine', answer: 'vỡ lẽ, thiếp' },
    { title: 'Various', answer: 'khác nhau, không giống nhau' },
    { title: 'Dissactisfaction', answer: 'bất mãn, không bằng lòng, không hài lòng' },
    { title: 'Explode', answer: 'làm nổ, đập tan, làm tiêu tan' },
    { title: 'Tremble', answer: 'run sợ, lo sợ' },
    { title: 'Conversation', answer: 'cuộc nói chuyện, đàm luận' },
    { title: 'Recall', answer: 'gọi về, triệu hồi, nhớ lại' },
    { title: 'Expect', answer: 'mong chờ, trông đợi' },
    { title: 'Adroad', answer: 'đi đến nước ngoài' },
    { title: 'Betrayal', answer: 'sự phản bội' },
    { title: `Won't`, answer: `will not` },
    { title: 'Deny', answer: 'phủ phận, từ chối' },
    { title: 'Troublesome', answer: 'quấy rấy, khó chịu' },
    { title: 'Entrust', answer: 'giao phó' },
    { title: 'Technician', answer: 'kỹ thuật viên' },
    { title: 'Several', answer: 'vài' },
    { title: 'Miscellaneous', answer: 'pha tạp, hỗn hợp, linh tinh' },
    { title: 'Charge', answer: 'sự gánh vác (chi phí, phí tổn)' },
    { title: 'Abort', answer: 'bỏ dở, sẩy thai' },
    { title: 'Bully', answer: 'ức hiếp, bắt nạt' },
    { title: 'Towards', answer: 'theo hướng, về phía, hướng về' },
    { title: 'Obtain', answer: 'đạt được, giành được, thu được' },
    { title: 'Whispering', answer: 'tiếng đồn bậy, tiếng nói thầm, tiếng thì thầm, tiếng xì xào, tiếng xào xạc' },
    { title: 'Establish', answer: 'lập, thành lập, thiết lập, kiến lập' },
    { title: 'Substance', answer: 'thực chất, cốt lõi, loại vật chất nào đó' },
    { title: 'Obediently', answer: 'ngoan ngoãn' },
    { title: 'Scratch', answer: 'cào, gãi' },
    { title: 'Attitude', answer: 'thái độ, quan điểm' },
    { title: 'Turn', answer: 'quay, sự thay đổi' },
    { title: 'Effort', answer: 'sự cố gắng, nỗ lực' },
    { title: 'Mind', answer: 'phản đối, cảm thấy phiền lòng, ý kiến, ý định, ý nghĩ' },
    { title: 'Proper', answer: 'thích đáng, thích hợp' },
    { title: 'Grab', answer: 'túm lấy, vồ lấy, giật lấy' },
    { title: 'Majesty', answer: 'vẻ uy nghi, vẻ oai nghiêm, bệ hạ' },
    { title: 'Back', answer: 'còn nợ lại, lưng' },
    { title: 'Backer', answer: 'người ủng hộ, người giúp đỡ' },
    { title: 'Obedient', answer: 'ngoan ngoãn, biết nghe lời, vâng lời' },
    { title: 'Corridor', answer: 'hành lang' },
    { title: 'Through', answer: 'suốt, xuyên qua, qua' },
    { title: 'Frank', answer: 'thẳng thắng, ngay thật' },
    { title: 'Cushion', answer: 'cái đệm' },
    { title: 'Big bug / big shot', answer: 'nhân vật quan trọng' },
    { title: 'Kind', answer: 'có lòng tốt, tử tế ,bản tính, loại, hạng, thứ' },
    { title: 'Minister', answer: 'bộ trưởng' },
    { title: 'Cabinet', answer: 'cái tủ có ngăn kéo' },
    { title: 'Yearly', answer: 'hằng năm' },
    { title: 'Wage', answer: 'tiền lương, tiền công' },
    { title: 'Palm', answer: 'lòng bàn tay' },
    { title: 'Workshops', answer: 'hội thảo' },
    { title: 'Workshop', answer: 'xưởng, chỗ làm việc' },
    { title: 'Income', answer: 'thu lập, lợi tức' },
    { title: 'Cover', answer: 'vỏ bọc, bìa, che' },
    { title: 'Considerable', answer: 'số lượng lớn, đáng kể, to tát, lớn lao' },
    { title: 'Reject', answer: 'loại bỏ, bác bỏ, không chấp thuận' },
    { title: 'Disgust', answer: 'làm ghê tởm, làm kinh tởm, làm phẩn nộ, làm căm phẩn' },
    { title: 'Something', answer: 'một điều gì đó, một việc gì đó' },
    { title: 'Without', answer: 'không có, không cùng, vắng, thiếu, mà không' },
    { title: 'Whisper', answer: 'tin đồn kín, tiếng đồn kín, nói thầm, xì xào' },
    { title: 'Throw', answer: 'ném, vứt' },
    { title: 'Existence', answer: 'tình trạng hoặc hiện thượng có thực, sự sống sót' },
    { title: 'Polite', answer: 'lễ phép, có lễ độ, lịch sự, lịch thiệp' },
    { title: 'Berserk', answer: 'nổi quạo, cáo tiết' },
    { title: 'Yell', answer: 'kêu la, la hét' },
    { title: 'Be aware of', answer: 'ý thức, nhận thức về' },
    { title: 'Sake', answer: 'mục đích, lợi ích' },
    { title: 'Territory', answer: 'lãnh thổ, đất đai, khu vực' },
    { title: 'Wonder', answer: 'muốn biết, tự hỏi, ngạc nhiên, kinh ngạc, lấy làm lạ' },
    { title: 'Surround', answer: 'vây quanh, bao vây' },
    { title: 'Treatment', answer: 'sự đối xử, đối đãi, sự điều trị, phép trị bệnh' },
    { title: 'Trouble', answer: 'điều lo lắng, phiền muộn, sự làm phiền, quấy rầy, khó chịu' },
    { title: 'Resolve', answer: 'kiên quyết làm gì đó, quyết định, giải quyết' },
    { title: 'Honour', answer: 'danh dự, danh giá' },
    { title: 'Floating', answer: 'nổi, thay đổi, di động' },
    { title: 'Guess', answer: 'đoán, phỏng đoán, ước chừng' },
    { title: 'Worth', answer: 'giá trị, tính hữu ích' },
    { title: 'Leisure', answer: 'thời gian rỗi, thời gian không phải làm việc' },
    { title: 'Actually', answer: 'trên thực tế, thực sự' },
    { title: 'Original', answer: 'nguyên bản chính, gốc, nguồn gốc, đầu tiên' },
    { title: 'Armour', answer: 'áo giáp' },
    { title: 'Abode', answer: 'vẫn còn, tiếp túc, ở lại, kéo dài' },
    { title: 'Console', answer: 'an ủi' },
    { title: 'Sudden', answer: 'thình lình, đột ngột' },
    { title: 'Commoner', answer: 'người bình dân' },
    { title: 'Common', answer: 'thông thường, phổ biến, chung, thuộc về' },
    { title: 'Though', answer: 'mặc dù, tuy nhiên, tuy vậy' },
    { title: 'Burden', answer: 'gánh nặng' },
    { title: 'Ambition', answer: 'tham vọng' },
    { title: 'Fact', answer: 'sự thật, sự việc, cơ sở lập luận' },
    { title: 'Idiot', answer: 'thằng ngốc, kẻ ngốc' },
    { title: 'Perhaps', answer: 'có lẽ' },
    { title: 'Besides', answer: 'ngoài ra' },
    { title: 'Entire', answer: 'rời bỏ (vị trí), nghỉ hưu' },
    { title: 'Political', answer: 'chính trị, thuộc về chính trị' },
    { title: 'Saint', answer: 'thần, thánh' },
    { title: 'Gaze', answer: 'nhìn chằm chằm' },
    { title: 'Avert', answer: 'ngoảnh mặt, xoay đi chỗ khác' },
    { title: 'Certainly', answer: 'chắc chắn' },
    { title: 'Chest', answer: 'cái rương, ngực' },
    { title: 'Cheek', answer: 'má, gò má' },
    { title: 'Slap', answer: 'cát tát, đánh' },
    { title: 'Horrible', answer: 'kinh khủng, tệ hại' },
    { title: 'Sittuation', answer: 'vị trí, tình huống' },
    { title: 'Noble', answer: 'quý tộc, cao quý' },
    { title: 'Honest', answer: 'trung thực, thành thật' },

    { title: 'Remark', answer: 'lời nhận xét, bình luận, phê bình' },
    { title: 'Ambush', answer: 'phục kích, chặn đánh, mai phục, bố trí' },
    { title: 'Annoying', answer: 'làm trái ý, làm khó chịu, làm bực mình, chọc tức' },
    { title: 'Absurd', answer: 'vô lý' },
    { title: 'Mub', answer: 'bùn, làm đục, khuấy đục' },
    { title: 'Duke', answer: 'công tước' },
    { title: 'Misunderstading', answer: 'sự hiểu lầm' },
    { title: 'Trick', answer: 'đánh lừa, trò gian trá, thủ thuật, bí quyết' },
    { title: 'Mingle', answer: 'trộn lẫn, lẫn vào' },
    { title: 'Nonchalantly', answer: 'sơ suất, thờ ơ' },
    { title: 'Attendant', answer: 'người phục vụ, người theo hầu, tham dự, có mặt' },
    { title: 'Wig', answer: 'bộ tóc giả' },
    { title: 'Tease', answer: 'trêu chọc, tìm cách khiêu khích' },
    { title: 'Relaxed', answer: 'thoải mái, thanh thản' },
    { title: 'Strange', answer: 'lạ, xa lạ, không quen biết' },
    { title: 'Fidgety', answer: 'bồn chồn, sốt ruột, lo lắng, đứng ngồi không yên' },
    { title: 'Cautious', answer: 'thận trọng, cẩn thận' },
    { title: 'Composure', answer: 'sự bình tĩnh, điềm tĩnh' },
    { title: 'Extravagant', answer: 'quá mức, quá độ, phung phí' },
    { title: 'Attire', answer: 'quần áo, đồ trang điểm' },
    { title: 'Relative', answer: 'có liên quan đến cái gì, tương đối' },
    { title: 'Intent', answer: 'ý định, mục đích' },
    { title: 'Responsibility', answer: 'sự chịu trách nhiệm' },
    { title: 'Lying', answer: 'nói đối, chỗ nằm' },
    { title: 'Idly', answer: 'lười nhác, vẩn vơ, vu vơ' },
    { title: 'Dodge', answer: 'né tránh, lẩn tránh, động tác di chuyển lắc léo' },
    { title: 'Bright', answer: 'sáng chói, sáng ngời' },
    { title: 'Excess', answer: 'sự vượt quá giới hạn, sự quá mức' },
    { title: 'Bow', answer: 'cúi đầu, khom lưng, quỳ gối' },
    { title: 'Panic', answer: 'làm cho ai đó hoảng sợ' },
    { title: 'Tolerate', answer: 'tha thứ, khoan dung' },
    { title: 'Heir', answer: 'người thừa kế' },
    { title: 'Sevant', answer: 'người hầu, người đầy tớ' },
    { title: 'Adorable', answer: 'đáng kính, đáng tôn thờ' },
    { title: 'Despite', answer: 'dù, mặc dù, bất chấp' },
    { title: 'Dissatisfied', answer: 'không bằng lòng, bất mãn' },
    { title: 'Extremely', answer: 'vô cùng, cực kỳ' },
    { title: 'Thorough', answer: 'kỹ lưỡng, thấu đáo, triệt để, tỉ mỉ' },
    { title: 'Crudely', answer: 'sơ sài, qua loa' },
    { title: 'Participate', answer: 'tham gia hoặc bị lôi cuốn vào hoạt động nào đó' },
    { title: 'Circumstance', answer: 'hoàn cảnh, trường hợp, tình huống' },
    { title: 'Amid / amidst', answer: 'giữa, ở giữa' },
    { title: 'Regarding', answer: 'về việc, đối với vấn đề gì đó' },
    { title: 'Aside', answer: 'sang một bên' },
    { title: 'Essential', answer: 'bản chất, thực chất, tính chất' },
    { title: 'Beforehand', answer: 'sẵn sàng, trước, sớm hơn' },
    { title: 'Engagement', answer: 'sự hứa hẹn, sự hứa hôn, sự cam kết' },
    { title: 'Extra', answer: 'nhiều hơn hoặc vượt quá cái bình thường, hơn thường lệ, cộng thêm' },
    { title: 'Observe', answer: 'quan sát, theo dõi, tiến hành' },
    { title: 'Conversation', answer: 'cuộc nói chuyện, trò chuyện, đàm luận' },
];
